image:
  repository: ghcr.io/yarilomail/mailfrom-milter
  tag: "e789385"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr2-pull-secret

replicaCount: 1

milterPort: 10031
metricsPort: 8081

# reject | discard | quarantine_header | accept
MF_ACTION: reject
REJECT_CODE: "421"
MF_SENDER_ADD: "yes"

logLevel: ""

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

postDeployTest:
  enabled: true
  credentialsSecret: "relay-mailfrom-creds"
